### ISSUE TITLE
BAD CSRF errors on bot start.

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#111]
they need investigating and fixing. that shouldn't be happening.

**Comment by RaceProUK** [comment]
I had a look a week or two ago. I turned on the debug output for `request`, and matched what is in the `X-CSRF-Token` header with what we're getting from `csrf.json`; it's always a match.
Couldn't think of anything else to try though.

**Comment by TwelveBaud** [comment]
Are we sure no bots/organics/cyborgs are sneaking in with their own CSRF-header requests or uses?

-----Original Message-----

**Comment by RaceProUK** [comment]
Like I said, I checked the headers; everything matches up
