### ISSUE TITLE
Add card drawing alongside the dice modules

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#112]
Because I want it

**Comment by AccaliaDeElementia** [comment]
interesting. i like the concept.

keeping the hands secret from other players would be annoying. there's no /whisper command for in channel private communications. and juggling private messages could be very annoying to players.

i look forward to seeing how you solve that ;-)

**Comment by yamikuronue** [comment]
Honestly, I was just going to do a straight port of https://github.com/yamikuronue/LogiosBot/tree/master/lib/Modules/LogiCards
