### ISSUE TITLE
Upgrade to nodejs 0.12 in ES5 mode

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#114]
NodeJS 0.12.3 has hit stable. Perform any necessary actions to upgrade to this version in ES5 mode.

ES6 can come later

**Comment by AccaliaDeElementia** [comment]
that was simple.

no changes necessary, however hunspell (used by spellar) does not support node v0.12 yet.

**Comment by RaceProUK** [comment]
They fixed that back in February: https://github.com/nathanjsweet/nodehun/issues/19
