### ISSUE TITLE
Dice explosion does not recurse

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#130]
Exploding dice has no option to re-roll again when the first reroll comes up with maximum dice. 

Two test failures:

 1) roll should continue exploding dice:
    AssertionError: Four die should be rolled for rerolls: expected [ 6, 6, rem
ve: [Function] ] to have a length of 4 but got 2

 2) roll should cap at 20 rerolls:
    AssertionError: Twenty die should be rolled for rerolls: expected [ 6, 6, r
move: [Function] ] to have a length of 20 but got 2

**Comment by AccaliaDeElementia** [comment]
Looks to be a test expectation error. ;-)

resolved by d8a8f2cea70765a6e893fde58c12f6fda39ac3f1
