### ISSUE TITLE
Buffer replies to combine multiple replies to single post

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#139]
browser.createPost() should buffer replies for a short period of time so multiple replies to the same post get merged into one reply. This prevents comment spam by triggering multiple bot actions with a single post

**Comment by RaceProUK** [comment]
IIRC from the discussion we had on Slack, we were intending to implement this as a map of some sort, where each bucket is keyed by topic ID and post number to reply to, with a resettable timeout per bucket; when the timeout expires, the bucket's emptied into a single post.

It's gonna be interesting with all the callbacks that'll also have to be called :confused:
