### ISSUE TITLE
Dedupe seems to be missing

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#155]
Let's put that back in, shall we?

**Comment by RaceProUK** [comment]
In v0.x, the dedupe was part of the Summoner module; it's never been core functionality.
This should be wrapped up with issue #150, methinks.

**Comment by AccaliaDeElementia** [comment]
the dedupe we're talking about is the bit here:

https://github.com/SockDrawer/SockBot/blob/master/discourse.js#L410

that generates an additional tag to put on each post to make it unique.

should include ISO date/time, owner, and sockbot version i think.
