### ISSUE TITLE
Proper user agent

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#156]
twelvebaud [8:38 PM] 
@accalia: a "proper" user agent and something about versions

twelvebaud [8:39 PM]
just so that any post-release issues can be easily tied to where they came from

**Comment by RaceProUK** [comment]
Depends on issue #157

**Comment by TwelveBaud** [comment]
What I have right now:
`SockBot/0.16 (Hazardous Hera; rv:abadbabe; owner:@accalia) @shadowmod/20150431`
(where `abadbabe` is the commit hash and `20150431` is the commit date, or the boot date if the commit date is unavailable.)

**Comment by RaceProUK** [comment]
I'm currently thinking
`SockBot 2.0.0 Smeghead, owner RaceProUK`

I can always tweak it :wink:

**Comment by RaceProUK** [comment]
Just changed it to
`SockBot/2.0.0 (Smeghead; owner:RaceProUK)`
to make it a bit more browser-like

**Comment by AccaliaDeElementia** [comment]
i think

`SockBot/$version$ (@$username$, owner:@$owner$) ($ISOBootDate$)`

would be a reasonable format, no?

**Comment by RaceProUK** [comment]
ISO Boot Date?

**Comment by RaceProUK** [comment]
I have `SockBot/$version$ ($releaseName$; owner:$owner$; user:$username$)` ready to go; I think that's enough. I don't see the need for the boot date; after all, browsers don't send it.

**Comment by AccaliaDeElementia** [comment]
good enough for me!

:shipit:

**Comment by RaceProUK** [comment]
\*is taking that as an OK to close the issue :smile:*

**Comment by TwelveBaud** [comment]
Are we going to be doing version number bumps with each major change? I included commit hashes since one version number could potentially implicate any of 400-500 commits spanning months of development time; without that sort of thing, how do we know what someone's running?

**Comment by yamikuronue** [comment]
We probably should, yeah. Any non-trivial change to Core should get a version bump, at least of the minor. Plugins have their own versioning, and ideally everyone uses my new SockMon to give a place where people can see hwo their bot is configured

**Comment by AccaliaDeElementia** [comment]
agreed here. version bumps should be more frequent with revision bumps (2.09.xx) being rather common and minor bumps (2.xx) being any time any significant feature is added or changed.

**Comment by AccaliaDeElementia** [comment]
Made an update to this today in cb65a83c4c29 that resolved a small bug in the useragent.

prior to this tweak user-agent was created at browser module include time which was before config file was read.
