### ISSUE TITLE
Decide version naming scheme for 2.0 series

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#157]
it should probably be different than 0.x series

**Comment by AccaliaDeElementia** [comment]
I'm thinking that we'll want to avoid depending on git for version detection as the docs i'm writing support gitless builds (particularly ones over NPM) (with apologies to @TwelveBaud's version code).

it may be better to hard code that value in as something that needs to get updated with each release, just as the version information in package.json will need to get updated

**Comment by AccaliaDeElementia** [comment]
also the 0.xx series was alliteraive/assonant pair of "mischevious synnonym (possibly several times removed)" and "female name" both beginning with the first letter of the latin names for the greek alphabet

probably not the best system to name the releases.... Suggestions welcome for a new pattern for post 1.0 versions (starting at 2.0 for rasins ;-) )

**Comment by RaceProUK** [comment]
We could load the version from the package.json, so there's only one place to maintain it

**Comment by TwelveBaud** [comment]
>  docs i'm writing support gitless builds (particularly ones over NPM) 

Although for some reason it isn't happening, version information is supposed to get stamped into version.js as part of the export-out-of-git process. It can only collect the version number if it's exported directly from that tag, but it always collects the committer, hash, and commit date.

> We could load the version from the package.json, so there's only one place to maintain it

+1

**Comment by RaceProUK** [comment]
As it turns out, storing it in the package.json makes it really easy to use anywhere we like:
`const packageInfo = require('./package.json');`
Then we just `packageInfo.version` and `packageInfo.longVersion`.

**Comment by RaceProUK** [comment]
Should point out I added the `longVersion` on dev only; it's for the naming scheme

**Comment by AccaliaDeElementia** [comment]
i'd swap `longVersion` to `versionName` or `codeName` stylistically, but either way i like that approach, less to go wrong

@TwelveBaud: how is that supposed to get stamped? is it something we can put into package.json so the publish to NPM process involves pushing the exported info?

**Comment by RaceProUK** [comment]
About two minutes ago I renamed `longVersion` to `releaseName` for that very reason :laughing:

**Comment by AccaliaDeElementia** [comment]
that works too!

any suggestions on how to select the release names?

`Angelic Ariel` was just a tailpull really. it is changeable

**Comment by RaceProUK** [comment]
I just put 'Smeghead' in so I had something to look at while putting it together :smile:

**Comment by TwelveBaud** [comment]
It can't be directly used in package.json but it could be massaged as part of a build script.

Because of an `export-subst` line in the `.gitattributes` file, when you run `git archive` to make a ZIP file the string with the `$`'s at the start of `version.js` has actual information substituted in instead of the `%` placeholders. The code detects that this has happened by the absence of `%`'s and breaks out the other information. If you archived a commit that was exactly pointed to by a tag, then the first part has `tag: whatever`, so that needs to be stripped off.

I think a better solution would be to have an optional build step that works with `git describe` but doesn't fail (and doesn't overwrite anything) if that information isn't available.

**Comment by AccaliaDeElementia** [comment]
@TwelveBaud: want to have a crack at working out what that build step would be?

**Comment by TwelveBaud** [comment]
Normally yes, but I'm doing disaster recovery at work, and have a long line of projects afterward, so I don't think I'll have time...

**Comment by AccaliaDeElementia** [comment]
hmm... okay then, i'll table the git introspection part of versioning for now. it's not blocking and we can add it in later.

**Comment by RaceProUK** [comment]
So we just need a naming convention...

**Comment by AccaliaDeElementia** [comment]
i'm open to ideas!

**Comment by RaceProUK** [comment]
How about we work through the alphabet, using this (https://en.wikipedia.org/wiki/List_of_fabric_names) as a source of names? So the first few releases will be Angora, Burlap, Canvas, Denim, and so on?

**Comment by AccaliaDeElementia** [comment]
That works for me. so 2.0 would be "Angelic Angora"

2.1 would be "Beautiful Burlap"

2.2 "Clairvoyant Canvas"

and so on....?

**Comment by RaceProUK** [comment]
Can do; I'll commit `Angelic Angora` as the first name

**Comment by AccaliaDeElementia** [comment]
i think this rates a :shipit: 

we have an open question for commit tagging in user agent, but that can be sorted out as part of a separate issue post 2.0.
