### ISSUE TITLE
Document end of life and deprecation for 0.x series

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#158]
Let's set a death date before we move to 2.0 and document it in this, the last release

**Comment by AccaliaDeElementia** [comment]
I like the idea of tagging this 0.99 instead of 0.17.
but that's just stylistic

as for EOL i's day support 30 days past migration of any given plugin to 2.0 or 120 days from release of 2.09, whichever is shorter. After which support is on "best effort" until early 2016.

thoughts?
