### ISSUE TITLE
Discourse in a box

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#159]
1. Cut a hole in a box
2. Put discourse in that box
3. Make sockbot open the box
and that's the way you do it!

(AKA: bundle a vagrantfile that will run a local discourse install so we can integration test against an actual Discourse instance before unleashing someplace that matters)

**Comment by AccaliaDeElementia** [comment]
Any progress on this one? this could come in very useful for the statsporn conversion i'll be starting soon.

**Comment by yamikuronue** [comment]
Some. Ish. Maybe. I can push what I have when I get home, it's in a local-only repo right now. I was going to wait until I figured out why the faux mailserver isn't working before I unleash its ugliness on the world

**Comment by yamikuronue** [comment]
Released at: https://github.com/SockDrawer/DiscoBox
