### ISSUE TITLE
SockBot should have a proper CLI

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#169]
there should be a proper CLI to launch SockBot.

**Comment by AccaliaDeElementia** [comment]
Posibly using yargs for argument parsing.

will probably be super simple for now, but gives us an entry point to add more advanced CLI functionality later.

**Comment by RaceProUK** [comment]
Covered by commit 6bb5907

**Comment by RaceProUK** [comment]
I've added one CLI switch, `--checkCfg`. And it does something completely unexpected: it checks the config :)
