### ISSUE TITLE
Refactor CLI handling

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockBot#185]
The code to validate CLI arguments was moved from `cli.js` to `app.js`. While that's OK for now, when more CLI options are added, *some* of the code may need to run in `cli.js` as well. So at some point, the `yargs` code needs to be moved into its own **ES5** module that is then `require`d into both `app.ls` and `cli.js`.

**Comment by AccaliaDeElementia** [comment]
putting this on the back burner with #186 for now. turns out to be a bigger task than i expected. will need to be a thing for 2.12 at the earliest i think.

**Comment by AccaliaDeElementia** [comment]
CLOSED-WONTFIX

Move to pure ES6 rendered this task moot.
