### ISSUE TITLE
Bot does not ignore article category

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#212]
this reply should not have been generated.

both the OP (PaulaBean) and the Category (Articles) should be ignored!

**Comment by AccaliaDeElementia** [comment]
https://what.thedailywtf.com/t/a-fever-on-a-crappy-day/50762/12?u=accalia

**Comment by AccaliaDeElementia** [comment]
Not a bug.

https://github.com/SockDrawer/SockBot/blob/e43dea4f5c3efda644383d1fe46a0faf8bb7fb4e/lib/utils.js#L201-L203

I am owner of Sockbot, so SockBot considers me to be TL9. therefore i pass this check.

oopsies.

**Comment by RaceProUK** [comment]
Seems this is a genuine issue after all:
https://what.thedailywtf.com/t/a-fever-on-a-crappy-day/50762/47?u=raceprouk

**Comment by AccaliaDeElementia** [comment]
hmm... i'll agree that's an issue.

looks like something isn't right in the filter on topic/filter on post functions in utils maybe. can you have a look @RaceProUK?
