### ISSUE TITLE
Error when anonymizing to a restricted topic eroneous

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#220]
https://what.thedailywtf.com/t/been-avoiding-the-article-topics/50801/30?u=accalia

The error produced when there is a post error is incorrect.

**Comment by RaceProUK** [comment]
Updated post-Jeffing link:
https://what.thedailywtf.com/t/zoidberg/4761/37?u=raceprouk

**Comment by RaceProUK** [comment]
Actually, this isn't an issue with posting to a restricted topic; it's because the user has tried to anonymously reply to the same PM chain they issued the request in

**Comment by AccaliaDeElementia** [comment]
I agree that we don't intend to cover this case so that it works, but we should ensure that the error is indicated that it was an error posting the anonymized reply not in parsing the intent.
