### ISSUE TITLE
Anonymize: cannot reply anonymously to PM

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#222]
https://what.thedailywtf.com/t/been-avoiding-the-article-topics/50801/32?u=accalia

This is probably of limited use, but cannot anonymously reply to a PM that the bot can see.

**Comment by RaceProUK** [comment]
Updated post-Jeffing link:
https://what.thedailywtf.com/t/zoidberg/4761/39?u=raceprouk

**Comment by RaceProUK** [comment]
Not a bug; it works already :smile:
