### ISSUE TITLE
SockBot should track uptime.

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#234]
SockBot should track uptime and report uptime and some other "useful" stats in response to the !status command.

Stats reported should be:
Uptime
Memory usage
Node version
System Architecture/platform

the process module will be helpful there
https://nodejs.org/api/process.html

other stats should include:
`Socks Folded` (random values or "calculated" from other stats)

as well as a couple of other randomly chosen "stats", such as
`Splines Reticulated`
`Cogs Thrown`
`Holes Darned`
`Stars Gazed`

**Comment by RaceProUK** [comment]
`Starts Gazed` or `Stars Gazed`?

**Comment by AccaliaDeElementia** [comment]
why not both?

CPU usage would also be something interesting to include: http://stackoverflow.com/questions/9565912/convert-the-output-of-os-cpus-in-node-js-to-percentage
