### ISSUE TITLE
Add option to suppress 'Unrecognised command' response

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockBot#251]
Example:
https://what.thedailywtf.com/t/testing-netbot-2-0/51171/7?u=raceprouk

In that scenario, it would have been better for @RPBot to have replied with a Markov chain instead of the command help

**Comment by RaceProUK** [comment]
Will need to figure out a proper solution to this; some may find the current behaviour more desirable, depending on their configured plugins

**Comment by RaceProUK** [comment]
Deferring; this is a more complex job than originally anticipated

**Comment by AccaliaDeElementia** [comment]
@RaceProUK i think we can close this one with the move to version 3.0.

Is this correct?

**Comment by RaceProUK** [comment]
Yep :wink:
