### ISSUE TITLE
Add the list of modules to the Help text

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#270]
For modules that don't have commands, it should be exposed in the Help command.

**Comment by AccaliaDeElementia** [comment]
additionally core modules should respond via help with information on their use.

I've got some ideas on this front so if you don't mind i'd like to steal this ticket?

**Comment by RaceProUK** [comment]
Wouldn't this be better in the `!status` command?

**Comment by AccaliaDeElementia** [comment]
modules should be listed in the !status command, yes.

but things like summoner or anonymize should be discoverable via `!help` as well. ;-)

**Comment by yamikuronue** [comment]
Go for it

**Comment by AccaliaDeElementia** [comment]
thanks! i'll gewt straight to work on this after.... y'know..... *work*

-sigh-

**Comment by AccaliaDeElementia** [comment]
resolved by #277
