### ISSUE TITLE
Fix plugin search to be more permissive on file paths

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#271]
found in SoclBotMafia, the syntax for adding local modules is unnesessarily.... weird.

fix it please!

**Comment by AccaliaDeElementia** [comment]
@yamikuronue: how should this work?

I see two options: 
1. plugin definitions beginning with a dot prefix (`./` on linux `.\` on windows) are resolved as relative paths to the location of the config file.
2. plugin definitions beginning with a dot prefix are resolved as relative paths to the current working directory.

Which one would be least surprising to the user? is there another option i'm missing?

**Comment by yamikuronue** [comment]
The former, because fuck if I know what the CWD is at any point in a
complex node script ;)

Actually, I'm kind of thinking to the install directory for the script.
Least surprise would be with this folder structure:
    thingy/node_modules/sockbot
    thingy/node_modules/plugin

Being able to say:
    plugin

And having it grab the entry point from
thingy/node_modules/plugin/package.json

**Comment by AccaliaDeElementia** [comment]
unless i very much miss my guess sibling installed node modules, such as you would see when sockbot and sockbotmafia are installed side by side, should just work (tm) like that.  I didn't do anything to break that functionality of `require()` on porpoise...

i'll base relative paths off the config file location and we'll see where we get to from there.

**Comment by yamikuronue** [comment]
Huh, I could have sworn that didn't work before, but it did when I just
tried it.

**Comment by AccaliaDeElementia** [comment]
okay...... so the behavior we have will be:

Plugin name begins with `/` it will be loaded via absolute path
Plugin Name begins with `./` or `../` it will be loaded as relative to the location of the config file
Otherwise plugin will be loaded preferentially from builtin plugins, falling back to default require resolution if not a builtin plugin.

Does this make sense?

**Comment by yamikuronue** [comment]
Sure :)

On Thu, Feb 4, 2016 at 11:26 AM, Accalia Elementia <notifications@github.com
