### ISSUE TITLE
Set Identifiable useragent for sockbot processes

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#290]
Currently sockbot 3.0 uses an empty useragent. It should identify itself with a useragent identifing itself, its version, who it's logging in as and who owns the bot

**Comment by yamikuronue** [comment]
It should include the string 'bot' so it gets appropriately rate-limited on
WTDWTF and similar instances

On Mon, Apr 4, 2016 at 12:47 PM, Accalia Elementia <notifications@github.com

**Comment by AccaliaDeElementia** [comment]
would something like `Sockbot/3.0.0 (Linux) (Login:sockbot owner:accalia)` be sufficent?

**Comment by yamikuronue** [comment]
Not sure, ask Ben?

**Comment by AccaliaDeElementia** [comment]
paging @BenLubar to the operating room.

@BenLubar  to the operating room for consultation please.

**Comment by BenLubar** [comment]
`Sockbot/3.0.0 (Linux) (Login:sockbot Owner:accalia)` contains the case insensitive string `bot`, so that'd work.

I can probably change the rate limiting settings for sockbots specifically if 0.1 requests per second (per IP and user-agent of matching user-agents) is too low.

**Comment by AccaliaDeElementia** [comment]
sounds good.

login flow for sockbot takes 3 requests.

* GET `/api/config`
  to get a valid CSRF token
* POST `/login`
  to login
* GET `/socket.io`
  to open the websocket

from there everything else goes over the websocket

so we'll go with that.

now to wander off to express-useragent to issue a PR to add a fallback parsing so sockbot shows up as something other than `unknown on OS`
