### ISSUE TITLE
SockBot v3.0 doesn't detect failed login

### ISSUE THREAD

**Issue by sjennison** [SockDrawer/SockBot#294]
SockBot v3.0 does not appear to detect a failed login - it will announce it successfully logged on despite not actually being successful. It will then show errors due to not being logged in.

Log below:
```
[2016-04-04T23:04:29.744Z] codinghorrorbot ready for login
[2016-04-04T23:04:31.584Z] codinghorrorbot login successful
[2016-04-04T23:04:32.549Z] {
        "message": "[[error:no-user]]"
}
```

**Comment by AccaliaDeElementia** [comment]
confirmed issue with detecting failed logins as successfull.
