### ISSUE TITLE
Enable Chats

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#300]
Should trigger events and commands from private chat messages

**Comment by psychobunny** [comment]
https://github.com/psychobunny/nodebb-plugin-rps-battle-rpg

I never went too far with this, maybe you can steal some code? :) I would send you PRs on my spare time if you'd integrate the idea

**Comment by AccaliaDeElementia** [comment]
hmm.... interesting.

basically a variation of Rock Paper Scissors Lizard Spock against a bot, or possibly 2player with the bot mediating?

yeah that should be doable. we'be got a plugin to help moderate Mafia games afterall.... ;-)

**Comment by psychobunny** [comment]
> or possibly 2player with the bot mediating?

mindblown.gif

**Comment by AccaliaDeElementia** [comment]
of course in order to do that properly we'd need to have support for an `/notice` analogue in multiuser chats.

otherwise you'd need three chats, two private ones with the bot and one public game. that would work too but would be a bit too much coordination for effective spontaneous games. ;-)

not that i'm *hinting* anything or anything

**Comment by psychobunny** [comment]
This is a high priority issue and I will look into this asap. 

Says me at 7pm on a Friday

**Comment by AccaliaDeElementia** [comment]
i get my best development after 1700 local.

**Comment by psychobunny** [comment]
And all the bug reports at about 9am? Sounds about right, in my case.

**Comment by AccaliaDeElementia** [comment]
ah. the bug reports... those and also the asking "okay, i know it works, but i've gotta ask Past-Accalia..... HOW THE File System Consistency checK DOES IT WORK?!"

:-D

**Comment by psychobunny** [comment]
Hey, I just close them and say something like they were probably doing it wrong. Works for me, you should try it

**Comment by AccaliaDeElementia** [comment]
/me prefers to close them with commits.

`git commit -m'fix #45267538' some/unrelated/file.js`

;-P

**Comment by psychobunny** [comment]
> #45267538

Geez, if you've racked up that many issues I'd do the same. Perhaps automated...

**Comment by AccaliaDeElementia** [comment]
This should be resolved in release 3.1.0-RC2 and higher.

**Comment by AccaliaDeElementia** [comment]
released as part of 3.1.0
