### ISSUE TITLE
NodeBB and bots 

### ISSUE THREAD

**Issue by psychobunny** [SockDrawer/SockBot#304]
Slightly relevant issue: https://github.com/NodeBB/NodeBB/issues/2304

It would be great if SockBot could be recognised as a bot by NodeBB so we can so stuff like ignore them from the unread page, and perhaps segment analytics on bot posts 

Feel free to close if this isn't the right place for this, as I imagine it's more of something that needs to be addressed on our end as opposed to yours. Food for thought though :)

**Comment by AccaliaDeElementia** [comment]
if biggora/express-useragent#56 ends up getting merged sockbot will be identified as a bot based off of its user agent string.

until that PR is accepted sockbot does identify itself via [useragent](https://github.com/SockDrawer/SockBot/blob/master/lib/app.js#L18-L25) so analytics should pick it up even if it's not explicitly called out as a bot.. ;-)

An example SockBot user agent as of version 3.1.0-RC1:
`sockbot/3.1.0-RC1 (linux x64) (nodejs v5.10.1) (v8 v4.6.85.31) (user:sockbot owner:accalia)`

I'm open to making further changes to help in this matter as you sort out how such groups and analytics would be handled in nodebb.

i think for now it's best to defer this until nodebb figures out how it wants to handle the underlying issue, we can revisit this issue then, and in the mean time this issue will remain open for further comment.

**Comment by yamikuronue** [comment]
The PR was merged. Sockbot is now identified as a bot. Future enhancement requests to support future bot functionality are always welcome, but for now, I'm going to close this ticket.
