### ISSUE TITLE
Forum providers should include quoting methods

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#309]
Ideally, as a plugin, I could pass some text to the forum provider as a string, and get a version of the string back that, when inserted into a post, marks that text as a quote.

Examples:

provider | input | output
----------- | ------- | --------
phpBB | "This is a quote" | "[quote] This is a quote [/quote]"
nodeBB | "This is a quote" | "> This is a quote"
IRC | "This is a quote" | "This is a quote"

**Comment by AccaliaDeElementia** [comment]
acknowledged.
