### ISSUE TITLE
Forum providers should be able to generate a post link in the correct format

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockBot#310]
I'm thinking there should be a function to generate links, which could have two overloads:
`function generatePostLink(postId)`
`function generatePostLink(threadId, postIndex)`

That way, plugins can generate links to include in replies in a platform-agnostic manner

**Comment by AccaliaDeElementia** [comment]
acknowledged.

**Comment by AccaliaDeElementia** [comment]
@RaceProUK do you mind if i steal this one from you, i've got an idea for #309 that will get this one more or less for free?

if not, mind waiting a day so i can get #309 to the point you can plug this one into it?

**Comment by AccaliaDeElementia** [comment]
@RaceProUK can you give this solution a quick shufti?

i think it's ready for release in 3.2.0 for plugins to use.

**Comment by RaceProUK** [comment]
My only concern is the names of the exports; `urlForTopic` sounds like it should go to the top of the topic, not a specific post

**Comment by AccaliaDeElementia** [comment]
hmm..... yeah i can see that, that one will generate both kinds of links.... i thought the parameters would differentiate that fine though....

any suggestions for a better name?

**Comment by AccaliaDeElementia** [comment]
Yami, can you take a quick look at this one and tell me if it's sufficient for sockMafia?

**Comment by yamikuronue** [comment]
Looks good to me :)

**Comment by AccaliaDeElementia** [comment]
vunderbar. we'll table the naming concern for now to revisit later.

in the mean time: ship it

;-)
