### ISSUE TITLE
Forum providers should provide formatting methods

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#311]
As with #309 forum providers should provide text formatting functions so plugins can format text in a provider agnostic manner.

this should include:

* [ ] Links
* [ ] images
* [ ] spoilers
* [ ] Headers
* [ ] bold
* [ ] italic
* [ ] inline code block
* [ ] code block
* [x] quote - Resolved as of f03f9c7

**Comment by RaceProUK** [comment]
While a good idea, we should be careful not to effectively create our own SockBotML :wink:

**Comment by AccaliaDeElementia** [comment]
ooooh... now there's an idea..... a forum agnostic formatting language that can be parsed into any necessary output configuration ever.....

i shall call it [SockCode](https://en.wikipedia.org/wiki/BBCode)
