### ISSUE TITLE
Create a template provider for use by other developers as a base

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#312]
As a developer of sockbot providers i want a base repository to fork that gives me the minimum required code structure without any code behind it so that i can quickly create the necessary code for any forum as a sockbot provider

**Comment by yamikuronue** [comment]
Is this done given https://github.com/SockDrawer/sockbot-provider-example ?

**Comment by AccaliaDeElementia** [comment]
it will be done fia that provider example...... if i ever finish it....

:-(

ticket still in progress, issue still extant.

**Comment by AccaliaDeElementia** [comment]
Dear near future @AccaliaDeElementia,

You should use this ticket to test out implementations of #344 as part of discovery for that issue as the example provider will be bare of all implementation details, allowing the design patterns to be more easily seen and discussed.

Scincerely,
present @AccaliaDeElementia
