### ISSUE TITLE
Feature Request: Private message shortcut

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#314]
In the User interface, a way to alias "private message this user, for whatever definitions the provider uses for private messages" would be handy. The only guarantee is that the method will reject if there is no way to privately contact someone

**Comment by AccaliaDeElementia** [comment]
@errorx666, this one's been in the queue for a while now, would you be interesting in taking it?

I'm thinking the NodeBB Implementation would more or less be a straight proxy to [forum.Chat.create](https://github.com/SockDrawer/SockBot/blob/e3398065e3def5c5154c95ce51a7942b58cf083e/providers/nodebb/chat.js#L347), possibly with a sprinkling of `ChatRoom.rename()` after the create to set a custom chat room name.

**Comment by errorx666** [comment]
@AccaliaDeElementia The mention got lost in the notification deluge, so I didn't see this until now.  Sorry.

I need to figure out how to get Github to stop spamming me with all activity across all repositories...

**Comment by yamikuronue** [comment]
![image](https://cloud.githubusercontent.com/assets/1219256/17298128/a7ac1cf6-57d6-11e6-989c-bb899a8ac6ab.png)

**Comment by AccaliaDeElementia** [comment]
@errorx666  no worries. notification spam happens. ;-)
