### ISSUE TITLE
Command case issues

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#324]
My module called

```
forum.Commands.add('listVotes', 'list all votes from the day\'s start', this.listVotesHandler.bind(this));
```

I ran the command
```
@yamibot listVotes
````

I got the output
```
sockbot:commands executing command "listvotes" +41ms
sockbot:commands executing default handler for unrecognized command listvotes +0ms
```
to the console.

Either the bot should preserve the case I registered, or it should also lowercase the name when I register it to make it case-insensitive.

**Comment by AccaliaDeElementia** [comment]
Also, i'll let you register commands in any case too: 2dcc0cc8a3
