### ISSUE TITLE
Allow Multiword commands

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#327]
Commands are currently one word only. they should allow multiple words to be a command.

This was split from #306 as that issue contained multiple separate issues.

**Comment by AccaliaDeElementia** [comment]
hmm..... the more i think about this one the more i see the YAGNI principle applying.

shelving this one for now. will reopen if a need for the feature emerges

**Comment by yamikuronue** [comment]
YAGNI? This was inspired by mafia, whose interface is getting hideously complex. I wanted things like "list players" instead of "list-players" .

**Comment by AccaliaDeElementia** [comment]
..... OH! that's why we wanted it.

i just had that it was wanted..... not anything related to a use case for it....

hmm......

hrmmm.......

let me thing on this one then.

**Comment by AccaliaDeElementia** [comment]
initial support via external helper:

https://github.com/SockDrawer/sockbot-helper-nestedcommands


Example usage of the helper:
```
        const NestedCommand = require('sockbot-helper-nestedcommands');
        const cmd = new NestedCommand('test');
        cmd.add('one', makeHandler('one'), 'say `one`');
        cmd.add('two', makeHandler('two'), 'say `two`');
        return forum.Commands.add('say', 'say certain words', cmd.handler);
```

I think this should resolve the use case you wanted @yamikuronue. can you confirm and/or comment?

**Comment by AccaliaDeElementia** [comment]
@yamikuronue have you had a chance to look at the above mention repo to see if that functionality would suffice for handling multiword (nested) commands?

If so i think I would like to flesh that repo out more fully and make it the official way to nest commands/make multiword commands, that's the sort of functionality i'd like to keep out of core if it's relatively easy to implement in a helper package like that.

**Comment by yamikuronue** [comment]
eh, I plan to move toward a more robust parser anyway, so while I haven't, let's say it does?

**Comment by AccaliaDeElementia** [comment]
heh. fair enough then.

**Comment by AccaliaDeElementia** [comment]
Closing as per discussion on the 8th of August.
