### ISSUE TITLE
Remove Derpy from the logs

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#329]
Derpy is cute, but very large, and it makes it hard to see what time the error occurred when you're just tailing a log file. Can the line with the actual error get a timestamp? Thanks

**Comment by AccaliaDeElementia** [comment]
Will fix by removing derpy from the logs.

while fun she's rather unprofessional and couterproductive to the intended purpose of logging things.

**Comment by yamikuronue** [comment]
While that helps, my use case for long-running bots is to run pm2, so what I'm looking at is the last output to STDERR, which I assume will still get derpy?

**Comment by AccaliaDeElementia** [comment]
No, derpy will be removed entirely, this decluttering the event log.
