### ISSUE TITLE
Feature: Bot Compatible UserAgent String

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#332]
https://what.thedailywtf.com/post/919325

Sockbot should annoucne itself as `(nodebb/compatible)` as well as `(wtdwtf/compatible)`

Suggested by @abarker-TDWTF (who is more than welcome to open these himself. ;-) )

**Comment by BenLubar** [comment]
That works, but the actual suggestion is to look for the string `wtdwtf` anywhere in the user-agent.

**Comment by yamikuronue** [comment]
You might want to make the former one added by the provider

**Comment by AccaliaDeElementia** [comment]
@yamikuronue i was actually planning on having both added by the provider, since your slack provider isn't wtdwtf compatible. ;-)

@BenLubar yes, this solution is more than asked for, makes it more flexible for later. ;-)
