### ISSUE TITLE
Feature: Command.getRoom

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#340]
When a command is issued from a chat, there is no way to get the room ID. It is recorded, but cannot be retrieved. 

This could be overloaded into the Topic id, but if so, let me know, because I'm currently using that to distinguish a chat from a topic and would thus need another solution.

**Comment by AccaliaDeElementia** [comment]
hmmm.... from the command handler you should have access to the command object itself.

assuming you receive it as `command` you should be able to access the topic/chatroom/user ids via

`command.parent.ids`

in the case of a command received from a chat this should have the `room` key populated with a non negative value,

Is this sufficient for your goals?
