### ISSUE TITLE
Fix: Better reject message when there is no X and I call X.get()

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#341]
In the NodeBB provider, when a command is issued in a chat, and I call command.getTopic(), the error that comes back is not intuitive.

**Comment by AccaliaDeElementia** [comment]
Increasing scope to cover all objects in the nodeBB provider

calling .get() on any object should result in sensible error messages not just the error message from nodebb wrapped up in a JS Error object.
