### ISSUE TITLE
Providers should be able to advertise capabilities

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#345]
As a plugin author, I want to know if the current provider offers a capability (like Chats or Topics) before I attempt to use it. This should ideally be available during the Activate method call, so i can reject that if I cannot be activated on this provider.

**Comment by yamikuronue** [comment]
I kind of picture this working like:

```
Capabilities: {
   Chat: false,
   Post: {
        bookmarks: false,
        votes: false,
        delete: true
   }
}
````

so you can query arbitrarily deep

**Comment by AccaliaDeElementia** [comment]
agreed. this is an issue we want to solve.

however i would actually suggest implementing it such that providers implement a capability query functionality.

something like

```
forum.supports('Chat.GroupChat'); // returns true for providers that support multi-user chats
forum.supports('Post.Edit'); // Returns False for Write Once forums
forum.supports('Jack.Skellington'); // returns false, that's not a valid capability so of course it's not supported.
```

**Comment by yamikuronue** [comment]
Sure, that works as well :) As long as it's hierarchical like that so you can query either the whole concept (like, 'do you have Chats') or some subset.

**Comment by AccaliaDeElementia** [comment]
i would say yes it should be hierarchical to within some limit of nesting.

i would say that the spec should guarantee ten levels of nesting and providers are free to reject queries deeper than that if they wish (to allow the provider to protect itself against ReDOS attacks without violating the spec)

off the top of my head..... the spec should be something like this:

A valid supports query is:

* A period delimited, case insensitive string
* Up to ten tokens long
* Prefix queries test the existence of _any_ capability with that prefix
* Queries that do not resolve along a supported chain of capabilities are to be reported as not supported
  * Queries may terminate early once they reach an unsupported token
* Queries must resolve synchronously
* Queries may be made in bulk using an array of queries, these queries must resolve synchronously and the result must be an array of the same length and ordering as the input

**Comment by yamikuronue** [comment]
Ten tokens is more than enough for me :D 

I would say, an array of queries should be an "all" action: true or false if all those are supported. That seems to be the most common use.

**Comment by yamikuronue** [comment]
Also, some things that aren't methods should be supported, like `Post.markdown` or `Post.multiline`
