### ISSUE TITLE
Login was definitely NOT successful

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#377]
I got the following log messages:

```
3|yamibot  | [2016-10-20T14:17:29.850Z] yamibot ready for login
3|yamibot  | [2016-10-20T14:17:40.857Z] yamibot login successful
3|yamibot  | [2016-10-20T14:17:42.839Z] A-derp! Fatal Startup Error: E_USER_NOT_FOUND
```

and the bot does not seem to be getting notifications, but is pinging. Opening this issue to track my findings

**Comment by yamikuronue** [comment]
My name was all lowercase in the config that failed, and uppercased in a config that succeeded. I also had an IgnoreUsers block in the config that failed, which was not there in the old successful config. Making those two changes, the bot logged in successfully

**Comment by AccaliaDeElementia** [comment]
hmm. i keep meaning to issue a PR to nodebb to allow searching for usernames case insenitively...... then changing sockbot to use that instead of the current case sensitive method.
