### ISSUE TITLE
Malformed command triggers undefined error:

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockBot#396]
When using the logidice plugin the following command triggers a response that the command handler cannot deal with.

```
!roll @index&zwnj;d@index
```

this triggers the following error:

```
An unexpected error `Cannot read property 'join' of undefined` occured and your commands could not be processed!
```

**Comment by yamikuronue** [comment]
This is a duplicate of https://github.com/yamikuronue/SockLogiDice/issues/4 isn't it?

**Comment by AccaliaDeElementia** [comment]
yes it is duplicate from the ligidice side, this is also a bug in the command processing. :-) 

i'll remove you from this ticket though as you have an issue in logidice

**Comment by AccaliaDeElementia** [comment]
Determined that this error is *not* coming from SockBot Core and is in fact originating from SockLogiDice. Closing this issue in favor of yamikuronue/SockLogiDice#4
