### ISSUE TITLE
Request: commit message synonyms

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#417]
@AccaliaDeElementia asked me to document my request for synonyms in commit messages, like `feature:` for `feat:`

**Comment by AccaliaDeElementia** [comment]
@yamikuronue what synonyms would you like used for the current set of keywords?

  feat:     A new feature 
  fix:      A bug fix 
  docs:     Documentation only changes 
  style:    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc) 
  refactor: A code change that neither fixes a bug nor adds a feature 
  perf:     A code change that improves performance 
  test:     Adding missing tests or correcting existing tests
  build:    Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm) 
  ci:       Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs) 
  chore:    Other changes that don't modify src or test files 
  revert:   Reverts a previous commit 

Additionally what methods for determining breaking changes that would require a major version bump would you like to see. Currently the only way to indicate that is to include `BREAKING CHANGE: {description}` as a line in the commit message, would you like to see other methods for indicating this in commit messages

Finally: @AccaliaDeElementia, for the love of the GODDESS! Document these in contributing.md or readme.md for the future!

**Comment by yamikuronue** [comment]
Ideally it'd be case-insensitive, and `feature` would work for `feat`. The rest of them seem fine. 

To be honest, I've never put a BREAKING CHANGE notice in the commit message 😊

**Comment by AccaliaDeElementia** [comment]
.... if you never put a breaking change notice in a commit message how do you indicate that a breaking change has occurred?

I mean outside of needing that info for SemanticRelease to work correctly it's pretty damn valuable information for developers to find in the commit history.

**Comment by yamikuronue** [comment]
I've never committed a change that wasn't backwards-compatible since semrel was put in place :D

**Comment by AccaliaDeElementia** [comment]
if you did though..... how would you indicate it?

**Comment by yamikuronue** [comment]
Honestly not sure. At that point I'd probably be very cautious, and be likely to put up with `cz`'s extended workflow to make sure it got in there correctly.

**Comment by AccaliaDeElementia** [comment]
hmm. fair enough. so i can ignore that consideration for now.

okay, so basically:

* Ensure case insenitivity(without case smashing if possible)
* Allow `feature` as a synonym for `feat`

is requiring the colon after the commit type token acceptable? requiring `feature: wiggle the whatsits` instead of just `feature wiggle the whatsits`?

**Comment by RaceProUK** [comment]
I think the colon helps recognise the keyword easier

**Comment by yamikuronue** [comment]
the colon is fine :)

**Comment by AccaliaDeElementia** [comment]
vunderbar.

i will fix this.

**Comment by AccaliaDeElementia** [comment]
This was fixed in bd75044a68f9cdfd2b7631db1434faed67d0e124

@yamikuronue, can we close this issue now? :-)

**Comment by yamikuronue** [comment]
Sure
