### ISSUE TITLE
Auto-gen documentation

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#85]
Some sort of inline documentation that can be auto-genned into an API doc to make it pretty.

**Comment by yamikuronue** [comment]
@AccaliaDeElementia  How does http://hiking.luddites.me/2013/07/api-documentation-considered-evil.html look?

**Comment by AccaliaDeElementia** [comment]
that will help for code docs. and is something i really need to sit down and do.... probably should set myself a reward system for doing that.

something like no cookies or candy until i write docs and i need to complete the docs for a .js file to earn a cookie.

what about for documenting how to interact with the bots? that's a lot more complicated than writed the modules themselves. ;-)

**Comment by yamikuronue** [comment]
Well sure, but that's a matter for a regular page in the docs. I figure
start with the technically interesting challenge and branch out from there
:)

On Mon, Apr 20, 2015 at 7:32 PM, Accalia Elementia <notifications@github.com

**Comment by AccaliaDeElementia** [comment]
fair enough.

so i am reading that right that you want me to do the JS docs for you to generate the api from, or do you want to write the jsdoc comments?

or maybe a tag team where i write it and you come behind me and make it not so..... developerish?

**Comment by yamikuronue** [comment]
Any of those options work for me, but I'll point out that two cores are far
more efficient than a single-threaded machine ;)

On Mon, Apr 20, 2015 at 7:35 PM, Accalia Elementia <notifications@github.com

**Comment by AccaliaDeElementia** [comment]
huh.... well then i'll start in `/` ans you start in `/sock_modules` then?

ping me here, via mail, or on IRC if you need me to explain anything.

there's a fair bit of 1AM code in some of those modules.

.... there's some 3 and 4AM code in the core...

**Comment by RaceProUK** [comment]
If two cores are more efficient, surely three is even better…

In other words, I'll document the modules I've written :wink:

**Comment by yamikuronue** [comment]
I am frightened of this setup: https://github.com/thanpolas/grunt-github-pages

Can someone make this foolproof?

**Comment by AccaliaDeElementia** [comment]
i can take a look at it.


... first time i've touched Grunt though....

so... might take a while.

**Comment by yamikuronue** [comment]
Grunt I can do, it's the repo setup that scares me. You have to set up one brnach inside an ignored folder of another.

**Comment by RaceProUK** [comment]
That sounds like a recipe for disaster…

**Comment by AccaliaDeElementia** [comment]
oh... yeah that sounds like a do not want....

**Comment by yamikuronue** [comment]
The thing is, the docs live in a separate branch than the code. They have to, for github pages to work. So it makes sense I guess

**Comment by AccaliaDeElementia** [comment]
well that's easily sorted, but that repo setup..... yeah....

**Comment by yamikuronue** [comment]
oh! What if I can get grunt to bootstrap itself and do the checkout... that might work

**Comment by AccaliaDeElementia** [comment]
you're hooked already!

:-D

**Comment by yamikuronue** [comment]
Gruntfile committed. Need to sort out auth issues.

**Comment by yamikuronue** [comment]
This is how you sort out the auth issues: http://stackoverflow.com/questions/18027115/committing-via-travis-ci-failing

Any opposition to setting up travis in this manner?

**Comment by yamikuronue** [comment]
http://sockdrawer.github.io/SockBot/
