### ISSUE TITLE
[docs] Document math module

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#96]

**Comment by RaceProUK** [comment]
So using a list of issue IDs doesn't auto-close all the issues :unamused:

**Comment by yamikuronue** [comment]
If you commit to dev, it doesn't close until it gets merged into master

**Comment by RaceProUK** [comment]
I committed to `master` though

**Comment by TwelveBaud** [comment]
You have to put "Fixes" before each individual number, otherwise it just counts as a reference.

**Comment by RaceProUK** [comment]
Discosense

**Comment by yamikuronue** [comment]
Keywords for closing issues

The following keywords will close an issue via commit message:

   - close, closes, closed
   - fix, fixes, fixed
   - resolve, resolves, resolved

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by RaceProUK** [comment]
Yes, but if I fix multiple tickets in one commit, why can't I just go `Fixes #92, #95, #96`?

**Comment by TwelveBaud** [comment]
> # Closing multiple issues
>
> To close multiple issues, preface each issue reference with one of the above keywords.
> 
> For example, `This closes #34, closes #23, and closes example_user/example_repo#42` would close issues #34 and #23 in the same repository, and issue #42 in the "example_user/example_repo" repository.

**Comment by yamikuronue** [comment]
Speaking of, you messed up the module declaration,s o have another go at auto-closing ;)

**Comment by RaceProUK** [comment]
You reopened this just *after* I committed…

Also, I still don't see why `Fixes #92, #95, #96` can't autoclose #92, #95, and #96…
